# Generated by Django 4.1.5 on 2023-01-17 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('familyTree', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='Waalidka',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='familyTree.bigparent'),
        ),
    ]
