# Generated by Django 4.1.5 on 2023-01-17 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('familyTree', '0002_parent_waalidka'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='tiradaXaasaska',
            field=models.IntegerField(default=3),
        ),
        migrations.CreateModel(
            name='PChild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('magacDhamaysiran', models.CharField(max_length=255)),
                ('sawirka', models.ImageField(blank=True, null=True, upload_to='sawirada/waalidinta')),
                ('magacaHooyada', models.CharField(max_length=255)),
                ('magacKuGalid', models.CharField(max_length=255)),
                ('jinsiga', models.CharField(choices=[('wiil', 'WIIL'), ('gabar', 'GABAR')], default='wiil', max_length=255)),
                ('number', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('faahfaahin', models.TextField(blank=True, null=True)),
                ('Waalidka', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='familyTree.bigparent')),
            ],
        ),
    ]
