# Generated by Django 4.1.5 on 2023-01-17 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('familyTree', '0003_parent_tiradaxaasaska_pchild'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pchild',
            name='Waalidka',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='familyTree.parent'),
        ),
    ]
