# Generated by Django 4.1.5 on 2023-01-17 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('familyTree', '0004_alter_pchild_waalidka'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parent',
            old_name='Waalidka',
            new_name='waalidka',
        ),
        migrations.RenameField(
            model_name='pchild',
            old_name='Waalidka',
            new_name='waalidka',
        ),
    ]
