# Generated by Django 4.1.5 on 2023-01-17 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('familyTree', '0005_rename_waalidka_parent_waalidka_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='simBarent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='familyTree.parent'),
        ),
    ]
