# Generated by Django 4.1.5 on 2023-01-17 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familyTree', '0007_remove_parent_simbarent_parent_bigwaalid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='jinsiga',
            field=models.CharField(choices=[('wiil', 'WIIL'), ('gabar', 'GABAR')], default='wiil', max_length=255),
        ),
    ]
